language: go

env:
  - GO111MODULE=on
go:
- "1.12.5"

script:
  - make testrace
  - go test -coverprofile=coverage.txt -covermode=atomic ./...

deploy:
  provider: script
  script: curl -sL https://git.io/goreleaser | bash
  on:
    branch: master
    tags: true
    condition: "$TRAVIS_TAG =~ ^v"


after_success:
  - bash <(curl -s https://codecov.io/bash)